### ISSUE TITLE
Незатворен <span> таг

### ISSUE THREAD

**Issue by ignisf** [governmentbg/data-gov-bg#1]
Здравейте,

Забелязах, че в маркъпа на началната страница присъства незатворен `span` таг. Според спецификацията на HTML могат да не бъдат затваряни само следните тагове: [List of HTML void elements](https://www.w3.org/TR/html/syntax.html#void-elements)

Свързаният код е тук: 
https://github.com/governmentbg/data-gov-bg/blob/7fe9014e84da46cdbc395e18239f695b7c4259d7/resources/views/partials/js-translations.blade.php#L1-L14

**Comment by dimitardelchev93** [comment]
Здравей, благодарим за забележката, грешката е поправена и ще бъде качена със следващия release
